[package]
name = "building-native-applications-with-delta-lake"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
deltalake = { version = "0.15", features = ["datafusion"] }
arrow = { version = "45.0.0", features = ["prettyprint"] }